CREATE TABLE Report(
    ID VARCHAR(36) PRIMARY KEY,
    MobilePhone VARCHAR(255) NOT NULL,
    Latitude FLOAT NOT NULL,
    Longitude FLOAT NOT NULL,
    Comments VARCHAR(255) NOT NULL,
    Status VARCHAR(255) NOT NULL,
    Reason VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Address(
    ReportID VARCHAR(36) NOT NULL,
    Street VARCHAR(255) NOT NULL,
    StreetNumber VARCHAR(255) NOT NULL,
    Neighborhood VARCHAR(255) NOT NULL,
    City VARCHAR(255) NOT NULL,
    ZipCode VARCHAR(8) NOT NULL,
    State VARCHAR(2) NOT NULL
);

CREATE TABLE Image(
    ReportID VARCHAR(36) NOT NULL,
    URL VARCHAR(255) NOT NULL
)
