CREATE TABLE Report(
    ID VARCHAR(36) PRIMARY KEY,
    MobilePhone VARCHAR(255) NOT NULL,
    Latitude FLOAT NOT NULL,
    Longitude FLOAT NOT NULL,
    Comments VARCHAR(255) NOT NULL,
    Status VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Image(
    ReportID VARCHAR(36) NOT NULL,
    URL VARCHAR(255) NOT NULL
)
